[build-system]
requires = ["hatchling>=1.27.0"]
build-backend = "hatchling.build"

[project]
name = "vs_grain"
version = "2.1.0"
description = "Generate realistic film grain or overlay grain clips in VapourSynth."
readme = "README.md"
requires-python = ">=3.12"
authors = [{ name = "pifroggi" }]
license = "MIT"
license-files = ["LICENSE"]

keywords = [
	"vapoursynth",
	"video",
	"grain",
	"overlay",
	"filtering"
]

classifiers = [
	"Programming Language :: Python :: 3",
	"Topic :: Multimedia :: Video"
]

dependencies = [
	"vapoursynth>=74",
	"vapoursynth-akarin",
	"vapoursynth-vszipcu"
]

[project.urls]
Homepage = "https://github.com/pifroggi/vs_grain"
Repository = "https://github.com/pifroggi/vs_grain"
Issues = "https://github.com/pifroggi/vs_grain/issues"
